name: Stage Deploy

concurrency:
  group: stage_deploy
  cancel-in-progress: true

on:
  push:
    branches:
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - develop
    types: [closed]

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mssp
  DEPLOY_PATH: /MSPP
  DEPLOY_FOLDER: MSPP

defaults:
  run:
    working-directory: .

jobs:
  build-and-push-image-to-github-packages:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Sanitize repo slug
        uses: actions/github-script@v6
        id: repo_slug
        with:
          result-encoding: string
          script: return 'ghcr.io/${{ github.repository }}'.toLowerCase()
      - name: Push Stage to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}"
          push: true
          tags: ${{ steps.repo_slug.outputs.result }}:stage          

  deploy:
    name: Deploy changes on server
    runs-on: ubuntu-latest
    environment:
      name: stage_deploy
    needs: build-and-push-image-to-github-packages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: executing remote ssh commands to deploy
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_PUBLIC_KEY }}      
          command: |
            mkdir {{ env.DEPLOY_FOLDER }}
            cd ${{ env.DEPLOY_PATH }}
